export const CATEGORIES = [
  "Casse-tête",
  "Jeu d'Adresse",
  "Jeu d'Ambiance",
  "Jeu d'Enquête",
  "Jeu de Cartes",
  "Jeu de dés",
  "Jeu de lettres",
  "Jeu de plateau",
  "Jeu de tuiles",
  "Jeu à Griffonner",
  "Livre dont vous êtes le héros",
];

export const THEMES = [
  "Abstrait",
  "Alimentation",
  "Amérique Latine",
  "Angleterre",
  "Animaux",
  "Années 50",
  "Arts",
  "Asie",
  "Astronomie",
  "Atlantide",
  "Aventure",
  "Aviation",
  "Bande dessinée",
  "Bourse & Finances",
  "Catastrophe",
  "Champignons",
  "Chiffres",
  "Château",
  "Colonisation",
  "Commerce",
  "Conquête",
  "Construction",
  "Contemporain",
  "Contes",
  "Couleurs",
  "Course",
  "Criminalité",
  "Cuisine",
  "Dinosaures",
  "Démons",
  "Enfants",
  "Enquêtes & Mystères",
  "Environnement",
  "Escargots",
  "Espace",
  "Espagne",
  "Espionnage",
  "Exploration",
  "Fantastique",
  "Fantasy",
  "Fantômes & Esprits",
  "Far West",
  "Folklore",
  "Formes",
  "Fourmis",
  "Fromages",
  "Fruits & légumes",
  "Fées & lutins",
  "Fête",
  "Gangs",
  "Grenouilles & Crapauds",
  "Guerre",
  "Géographie",
  "Habitation",
  "Historique",
  "Horreur",
  "Humour",
  "Immobilier",
  "Incas",
  "Industrie",
  "Insectes",
  "Japon",
  "Jardinage",
  "Jeu vidéo",
  "Jungle",
  "Labyrinthe",
  "Les îles",
  "Littérature",
  "Loisirs",
  "Londres",
  "Loups-garous",
  "Mafia",
  "Magie & Sorcellerie",
  "Mammouths",
  "Maritime",
  "Mines",
  "Monstres & Créatures",
  "Mythologie",
  "Médical",
  "Médiéval",
  "Médiéval Fantastique",
  "Nains",
  "Nature",
  "Objets",
  "Océan",
  "Oiseaux",
  "Onirique",
  "Parc d'attractions",
  "Pays-Bas",
  "Paysage",
  "Pierres Précieuses",
  "Pingouins & Manchots",
  "Pirates",
  "Poissons",
  "Polar",
  "Portugal",
  "Princesses & Princes",
  "Prison",
  "Préhistoire",
  "Renaissance",
  "Robots & Mechas",
  "Royauté",
  "Saisons",
  "Santé",
  "Science-fiction",
  "Sciences",
  "Sports",
  "Survie",
  "Temporalité",
  "Terrorisme",
  "Trains",
  "Transport & voyage",
  "Trésor",
  "Urbanisme",
  "Vie quotidienne",
  "Vikings",
  "Ville",
  "Volcans",
  "Voleur",
  "Zoo",
  "Écologie",
  "Économie",
  "Écureuils",
  "États-Unis",
  "Évasion",
];

export const MECANISMES = [
  "Adresse & Dextérité",
  "Affrontement Direct",
  "Argumentation",
  "Association d'idées",
  "Asymétrie",
  "Blocage",
  "Bluff",
  "Calcul",
  "Campagne",
  "Capture",
  "Chance & Hasard",
  "Choix multiples",
  "Choix simultanés",
  "Collection",
  "Combinaison",
  "Communication Restreinte",
  "Connexion",
  "Conquête",
  "Construction",
  "Construction De Tableau",
  "Contrôle de zone",
  "Coopération",
  "Créativité & Imagination",
  "Dans Ta Face",
  "Dessin",
  "Draft",
  "Draft par Division",
  "Déduction",
  "Défausse",
  "Défis",
  "Déplacement",
  "Exploration",
  "Flip & Write",
  "Gages",
  "Gestion",
  "Gestion de main",
  "Gestion de ressources",
  "hexagones",
  "Jet De Dés",
  "Jeu caché",
  "Logique",
  "Majorité",
  "Marché",
  "Mouvement de point à point",
  "Mémorisation",
  "Narration",
  "Négociation",
  "Objectif secret",
  "Observation",
  "Papier & Crayon",
  "Parcours",
  "Pari",
  "Pioche",
  "Placement d'ouvriers",
  "Placement de cartes",
  "Placement de dés",
  "Placement de tuiles",
  "Placement Stratégique",
  "Planification",
  "Plateau modulaire",
  "Plis",
  "Points d'action",
  "Pouvoir",
  "Prise de risque",
  "Programmation",
  "Rapidité",
  "Roll & Write",
  "Réflexion",
  "Rôle secret",
  "Scénarios",
  "Semi-coopération",
  "Simultanéité",
  "Stop ou encore",
  "Stratégie",
  "Temps réel",
  "Tir à la corde",
  "Vote",
  "Échange & Troc",
  "Élimination",
  "Énigme",
  "Équipes",
  "Évolutif",
];

export const EDITEURS = [
  "3WS Games",
  "Alt Shift",
  "Ankama",
  "Antikalker",
  "Asmodee",
  "Bad Taste Games",
  "Bakakou",
  "Blam !",
  "Blue Cocker",
  "Blue Orange",
  "Board & Dice",
  "Bombyx",
  "Borderline Editions",
  "Catch Up Games",
  "Cocktail Games",
  "Cryptozoic Entertainment",
  "Days Of Wonder",
  "De Architecturart",
  "Deep Print Games",
  "Don't Panic Games",
  "Drei Hasen In Der Abendsonne",
  "Dv Giochi",
  "Edge Entertainment",
  "Exploding Kittens",
  "Filosofia",
  "Floodgate Games",
  "Galápagos Jogos",
  "Gameology",
  "Gigamic",
  "Grail Games",
  "Hans Im Glück",
  "Helvetiq",
  "Henbrandt",
  "Hurrican",
  "Ideal",
  "Idventure",
  "Iello",
  "Igiari",
  "Inside - Doug Solutions",
  "Intrafin Games",
  "Jumbo",
  "Kosmos",
  "La Boite De Jeu",
  "La Rose Des Jeux",
  "Le Scorpion Masqué",
  "Les XII Singes",
  "Libellud",
  "Loki",
  "Lookout Games",
  "Ludonaute",
  "Lui-Même",
  "Lumberjacks Studio",
  "Matagot",
  "Mixlore",
  "Multifaces Editions",
  "Nerdlab Games",
  "Nürnberger Spielkarten Verlag",
  "Oink Games",
  "Oka Luda",
  "OldChap",
  "Origames",
  "Oya",
  "Parker Brothers",
  "Pixie Games",
  "Plan B Games",
  "PlayPunk",
  "Prétexte",
  "Queen Games",
  "Ravensburger",
  "Renegade Game Studios",
  "Repos Production",
  "Road To Infamy Games",
  "Sand Castle Games",
  "Sit Down! Games",
  "Smart Games",
  "Space Cowboys",
  "Spiral Editions",
  "Starling Games",
  "Subverti",
  "Super Meeple",
  "The Op Games",
  "Thunderworks Games",
  "Ubik",
  "Week End Games",
  "Ystari Games",
  "Z-Man Games",
];
