export const CATEGORIES = [
  "Jeu d'Ambiance",
  "Jeu de Cartes",
  "Jeu de dés",
  "Jeu de lettres",
  "Jeu de plateau",
  "Jeu de tuiles",
  "Livre dont vous êtes le héros",
];

export const EDITEURS = [
  "3WS Games",
  "Alt Shift",
  "Antikalker",
  "Asmodee",
  "Blam !",
  "Cocktail Games",
  "De Architecturart",
  "Edge Entertainment",
  "Filosofia",
  "Gigamic",
  "Helvetiq",
  "Igiari",
  "Kosmos",
  "Loki",
  "Ludonaute",
  "Lumberjacks Studio",
  "Matagot",
  "Mixlore",
  "Nürnberger Spielkarten Verlag",
  "Origames",
  "Oya",
  "PlayPunk",
  "Prétexte",
  "Ravensburger",
  "Renegade Game Studios",
  "Repos Production",
  "Road To Infamy Games",
  "Subverti",
  "Week End Games",
  "Z-Man Games",
];

export const THEMES = [
  "Abstrait",
  "Alimentation",
  "Animaux",
  "Astronomie",
  "Catastrophe",
  "Colonisation",
  "Commerce",
  "Contemporain",
  "Couleurs",
  "Enquêtes & Mystères",
  "Escargots",
  "Espace",
  "Fantastique",
  "Fantasy",
  "Far West",
  "Formes",
  "Fromages",
  "Fruits & légumes",
  "Fées & lutins",
  "Grenouilles & Crapauds",
  "Historique",
  "Humour",
  "Insectes",
  "Labyrinthe",
  "Les îles",
  "Loups-garous",
  "Maritime",
  "Mines",
  "Médical",
  "Médiéval",
  "Médiéval Fantastique",
  "Nains",
  "Nature",
  "Objets",
  "Pierres Précieuses",
  "Pirates",
  "Poissons",
  "Princesses & Princes",
  "Royauté",
  "Santé",
  "Science-fiction",
  "Trains",
  "Trésor",
  "Évasion",
];
